### ISSUE TITLE
Use the version specified in package.json

### ISSUE THREAD

**Issue by robfuscator** [bjoluc/jspsych-builder#26]
I'm not sure if I'm missing something here, but would it be possible to use the version specified in `package.json` instead of specifying it there _and_ in the `@version` pragma?

From my standpoint I don't really see the benefit of this pragma. Right now, I have to think of multiple places to change the version before a release. If there is a valid reason this pragma exists, we could also use the version specified in `package.json` as a fallback in those cases where the pragma is omitted.

What do you think?

**Comment by jmuchovej** [comment]
I'm curious how you're deploying your experiment. I suggested (and am implementing, today) #22, but I haven't used `package.json` to control anything (since I end up exporting to JATOS, which only "references" the version in the export filename).

**Comment by bjoluc** [comment]
> From my standpoint I don't really see the benefit of this pragma. Right now, I have to think of multiple places to change the version before a release.

Valid point, if you only develop one experiment in a workspace and publish your code to NPM. However, since I think NPM publishing of application code is rather uncommon, the current [template package.json](https://github.com/bjoluc/jspsych-builder/blob/main/assets/template/package.tmpl.json) is set to `private` and doesn't specify a version anymore. The `name` and `version` fields in the old `package.json` template were only because I didn't know `private` back then...

The benefit of the `version` pragma is that it allows to independently bump versions of several experiments within the same workspace :slightly_smiling_face: Do you publish experiments to NPM? Otherwise, I'd just suggest getting rid of `version` in `package.json`.

Closing this as too specific. I see there are rare situations where it might be helpful – sorry if you're in such a situation – but I don't think the use case is common enough to maintain it.

**Comment by robfuscator** [comment]
Fair point. I'm not using workspaces, so I didn't think of that, thanks for pointing it out. :slightly_smiling_face:
