### ISSUE TITLE
Trouble integrating external-html plugin into timeline

### ISSUE THREAD

**Issue by d-bohn** [bjoluc/jspsych-builder#5]
Hello,

Thank you for packaging and supplying this builder! I'm trying to add an external-html (via the plugin that comes with jspsych) to the `createTimeline` function and I can't seem to figure it out. Here's what I included in the function:

```
export function createTimeline(input = {}) {

    // ...

    var check_consent = function(elem) {
        if (document.getElementById('consent_checkbox').checked) {
            return true;
        } else {
            alert(
                "If you wish to participate, you must check the box next to the statement 'I agree to participate in this study.'");
            return false;
        }
        return false;
    };

    // create timeline
    let timeline = [];

    var ifc = {
        type: 'external-html',
        url: "./consent.html",
        cont_btn: "start",
        check_fn: check_consent
    };

   timeline.push(ifc);
```

As you can see this is almost an exact copy of the example from the [external-html plugin page](https://www.jspsych.org/plugins/jspsych-external-html/) for jspsych. However, when I run the experiment, it hang son the "loading" screen and won't continue. I've tried including `consent.html` in the `src` and the `media/subfolder` folders, but the issue persists.

Any help would be appreciated. And apologies in advanced if it is a simple fix. I'm new to nodeJS coming from "straight" JavaScript.

**EDIT**:
I've run across a couple of other issues (`survey-multi-select`, writing to disk with `on_finish`), so I'd be grateful to discuss them with you, as I hope they will help others adopt this cli more readily!

**Comment by bjoluc** [comment]
Hi, glad you found this!
I see two potential problems here:

* I guess I didn't mention the need to import jsPsych plugins into your experiment file anywhere. Sorry! In order to include the `external-html` plugin in the resulting code bundle, you will need to `import "jspsych/plugins/jspsych-external-html";` somewhere at the top of your experiment file. This resolves to the corresponding jsPsych plugin file via Node.js module resolution (the equivalent to referencing it in an HTML script tag). To be precise, webpack, the primary tool behind jsPsych builder, resolves the corrsponding .js file from the `node_modules` directory and includes it in the JavaScript bundle (be it in development or production). I'll mention this in the docs soon. Thanks!
* You will need [@miscDir](https://github.com/bjoluc/jspsych-builder#media) to tell jsPsych builder to include your `media/subfolder`. Otherwise, the consent.html will not be included in any build (neither the development build you create with `jspsych run`, nor the `jspsych build` production one). The URL option of the `external-html` plugin needs to be `./media/subfolder/consent.html` then.

I noticed there's by far not enough documentation regarding the points above. I hope I'll find some time to improve the docs soon. Let's leave the issue open until then...

Off-topic:
* I find the browser console quite helpful to spot missing plugins; jsPsych usually complains with an error message there.
* Coming from vanilla JS, you may want to read about ES6 (and later standards) to learn about JavaScript modules and new helpful language features – you can use pretty much all of them with jsPsych builder, because WebPack transpiles the source code using Babel. [Here's](https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f) a fun read on that stuff :D

**Comment by d-bohn** [comment]
Thanks for your response and the resources your provided. That is very kind and generous of you!

The issue was related to your second point. It appears that the `./media/subfolder/consent.html` wasn't copied over correctly to `.jspsych-buiilder` when I used `jspsych run`. This happened a couple times as I was testing it out, but just manually copying over the subfolder fixed the issue. I'm not sure if the failure to copy everything is isolated to my system or not. I haven't been able to reproduce the issue on another machine yet.

I had one additional question that is not related to the topic of the `external-html` plugin (if you want me to put it in another issue I can). In vanilla javascript I can use [a php script](https://www.jspsych.org/overview/data/#storing-data-permanently-as-a-file) to write the data to disk on the server that is hosting the experiment. However, when I try using those same scripts in the nodeJS file, it doesn't appear to be saving. I'm pretty sure it is a path issue, as the browser debugger can't find the php file (404). I've tried including the php scripts in a subfolder of `src` as well as in a subfolder of `media` (again manually copying them over when the fail to do so). Do you have any suggestions/examples of how to include php scripts to write to disk once the apps is bundled? Thanks!

**Comment by d-bohn** [comment]
I just built the app (keeping the php scripts in the media subfolder) and it appears to work now. It might have just been an issue the local development build! Thanks!

**Comment by bjoluc** [comment]
You're most welcome!

> It appears that the `./media/subfolder/consent.html` wasn't copied over correctly to `.jspsych-buiilder` when I used `jspsych run`. 

Currently, jspsych builder only copies the assets over at the beginning of `jspsych run` before the development server is started. Hence, changes to the pragmas or the media files only take effect when `jspsych run` is issued the next time. I have plans to improve this though. Until then, does re-running `jspsych run` fix the copying issue for you?

>In vanilla javascript I can use [a php script](https://www.jspsych.org/overview/data/#storing-data-permanently-as-a-file) to write the data to disk on the server that is hosting the experiment. However, when I try using those same scripts in the nodeJS file, it doesn't appear to be saving. I'm pretty sure it is a path issue, as the browser debugger can't find the php file (404).

The webpack development server that jspsych builder uses for `jspsych run` is not a full-featured web server like Apache and friends. Asset files are just served statically, meaning there's no server-side magic like PHP execution involved. I guess it does not even accept POST requests, which may be the reason for the 404 error (although, technically, it should better be 405 in that case).

> Do you have any suggestions/examples of how to include php scripts to write to disk once the apps is bundled? Thanks!

Unfortunately not, but if you would like to export a different `on_finish` function for production than for development, I'm happy to implement that. We could for instance have `on_finish` for development only, `on_finish_production` for regular production builds, and `on_finish_jatos` for JATOS builds. What do you think?

Despite that, I can highly recommend [JATOS](https://www.jatos.org/) as a web server for online experiments. Not only is it a very convenient tool to host experiments and access their results, it also integrates seamlessly with jspsych builder. They currently provide a [free experiment server](https://www.jatos.org/JATOS-server-during-the-COVID-19-pandemic.html) until the end of this year.
